config/routes.rb
Rails.application.routes.draw do
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :current_todo, only: [:show, :edit, :update, :destroy]

  def index
    @todos = Todo.all
  end

  def show

  end

  def new
    @todo = Todo.new
  end

  def create 
    todo = Todo.create(todo_params)
  end

  def update 
    @todo.update(todo_params)

    redirect_to todo_path(@todo)
  end

  def edit

  end

  def destroy
    @todo.destroy

    redirect_to todo_path
  end 

  private 

  def todo_params
    params.require(:todo).permit(:name, :description, :completed)
  end 

  def current_todo 
    @todo = Todo.find(params[:id])
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h3>Update Todo Details</h3>
<%= form_with model: @todo do |form| %>
  <%= form.text_field :name %>
  <%= form.text_field :description %>
  <%= form.label "Do not check if task is not completed." %>
  <%= form.check_box :completed %>
  <%= form.submit %>
<% end %>

app/views/todos/index.html.erb
<table>
  <% @todos.each do |todo| %>
    <tr>
      <td><%= link_to todo.name, todo_path(todo) %></td>
      <td><%= button_to 'Edit', edit_todo_path(todo), method: 'get'%></td>
      <td><%= button_to 'Remove', todo_path(todo), method: 'delete', data: { confirm: 'Are you sure?'} %></td>
  <% end %>
</table>
<%= link_to "Add a New Todo", new_todo_path %>

app/views/todos/new.html.erb
<h3>Create a Todo!</h3>
<%= form_with model: @todo do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :description, placeholder: "description" %>
  <%= form.label "Do not check if task is not completed." %>
  <%= form.check_box :completed %>
  <%= form.submit %>
<% end %>

app/views/todos/show.html.erb
<div>
  <h2> Name: <%=@todo.name%> </h2>
  <p> Description: <%=@todo.description%> </p>
  <p> Completed:
  <% if @todo.completed %>
    <%="Yes"%>
  <% else %>
    <%="No"%>
  <% end %> 
  </p>  
  <%= link_to 'Remove', @todo, method: :delete, data: { confirm: 'Are you sure?'} %>
</div>